"""empty message

Revision ID: d2f635b8eedd
Revises: ce97c6069411
Create Date: 2024-05-13 14:37:59.962954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f635b8eedd'
down_revision = 'ce97c6069411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('under_water_housing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_water_housing_table')
    # ### end Alembic commands ###
